blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/goodolclint/PSProxmoxVE/discussions
    about: Ask questions and discuss features in GitHub Discussions
