<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>PSProxmoxVE</RootNamespace>
    <AssemblyName>PSProxmoxVE</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PSProxmoxVE.Core\PSProxmoxVE.Core.csproj" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="PowerShellStandard.Library" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PSProxmoxVE.psd1" CopyToOutputDirectory="PreserveNewest" />
    <None Include="PSProxmoxVE.format.ps1xml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="PSProxmoxVE.dll-Help.xml" CopyToOutputDirectory="PreserveNewest" Condition="Exists('PSProxmoxVE.dll-Help.xml')" />
  </ItemGroup>

</Project>
